### PR TITLE
Create reverse_string.py

### PR DESCRIPTION
**Pull request by Chaitanya-087**

### CODE REVIEW

**Comment by Ashutosh-Tester** [comment]
def reverse_string(s):
  word_arr = s.split(" ")
  word_arr.reverse()
  return " ".join(word_arr)

You haven't called & passed any string argument in the function reverse_string(s)

**Comment by Chaitanya-087** [comment]
sure i will do

**Comment by Ashutosh-Tester** [comment]
word_arr = s.split(" ")
  word_arr.reverse()
  return " ".join(word_arr)


#demo
sample = "My name is xyz"
print(reverse_string(sample))

Man this time you removed the function reverse_string(_parameter)

**Comment by Chaitanya-087** [comment]
no i did not remove scroll to top

**Comment by Ashutosh-Tester** [comment]
Yes you were right .

**Pull request merged**
