### PR TITLE
WAP to print & count the longest increasing subsequence

### PR DESCRIPTION
**Pull request by aCrazyPOTATO**

### CODE REVIEW

**Comment by Ashutosh-Tester** [comment]
I didn't raised any issue for this.

**Comment by Ashutosh-Tester** [comment]
If you want to contribute something then try to solve the question longest increasing subsequence. You can find the detailed description of the problem in the issue section.

**Comment by aCrazyPOTATO** [comment]
@Ashutosh-Tester  I have add Program to print & count the longest increasing subsequence.

**Comment by Ashutosh-Tester** [comment]
Copied the whole code from geekforgeeks.

**Pull request merged**
