### PR TITLE
 Heart Pattern.py

### PR DESCRIPTION
**Pull request by anush8858**
Heart pattern using turtle technique in python

### CODE REVIEW

**Comment by Ashutosh-Tester** [comment]
Solve any question from the issue section and submit the code.

**Comment by anush8858** [comment]
@Ashutosh-Tester All the issues are hacktoberfest accepted than how will I solve it??

**Comment by Ashutosh-Tester** [comment]
what's the problem in that

**Comment by Ashutosh-Tester** [comment]
the two tags are given to the code which are able to be merged so that it could count in hacktoberfest event.

**Pull request merged**
